### ISSUE TITLE
Snapshot resource is missing for chromium browsers

### ISSUE THREAD

**Issue by eljamm** [asciimoo/omnom#43]
## Configuration

<details><summary>config.yml</summary>
<p>

```yaml
app:
  log_level: "info" # possible values: error, warning, info, debug, trace
  results_per_page: 30
  disable_signup: false # set to true to restrict user creation to command line
  template_dir: "./templates"
  static_dir: "./static"
  webapp_snapshotter_timeout: 15 # seconds
  debug_sql: false
server:
  address: "127.0.0.1:7331"
  # e.g. https://mydomain.tld/xy/
  # leave blank if you don't have custom base URL
  base_url: ""
  secure_cookie: true
  # Trust any username sent in this header. Only for use behind an authenticating proxy!
  # remote_user_header: "Remote-User"
db:
  type: "sqlite"
  connection: "./db.sqlite3"
storage:
  type: "fs"
activitypub:
  # Note: Omnom going to generate these keys in case files can't be opened
  pubkey: "./public.pem"
  privkey: "./private.pem"
```

</p>
</details> 

<details><summary>Extension Options</summary>
<p>

```
- Token: addontoken
- Save as public by default: true
- Omnom server URL: http://localhost:7331/
- Debug mode: true
```

</p>
</details> 

## Steps to Reproduce

I can reproduce this on `v0.4.0` and the latest master branch.

- `go build`
- `./omnom listen --config ./config.yml`
- `./omnom create-user user user@127.0.0.1`
- `./omnom set-token --config ./config.yml user login usertoken`
- `./omnom set-token --config ./config.yml user addon addontoken`
- Go to [a webpage](https://www.wikipedia.org/)
- Click on extension and
  - set `public: true` 
  - specify Snapshot title
- Take a snapshot
- Go to `http://127.0.0.1:7331/my_bookmarks`
- Open snapshot

## Expected behavior

A 1:1 representation of the page is loaded when clicking on the snapshot.

## Encountered behavior

Snapshot page is missing resources.

## Comparison

<details><summary>Original</summary>
<p>

![Image](https://github.com/user-attachments/assets/2743760d-4d3a-49d8-af33-35d5fa2f275f)

</p>
</details> 

<details><summary>Snapshot</summary>
<p>

![Image](https://github.com/user-attachments/assets/a5316cbb-78c8-4f9f-94c8-14afe912daec)

</p>
</details> 

## Logs

<details><summary>Server logs</summary>
<p>

```shellSession
2025/05/21 17:49:55 /home/user/omnom/model/bookmark.go:40 record not found
[0.077ms] [rows:0] SELECT * FROM `bookmarks` WHERE url = "https://www.wikipedia.org/" and user_id = 1 ORDER BY `bookmarks`.`id` LIMIT 1
[GIN] 2025/05/21 - 17:49:55 | 200 |   47.574733ms |       127.0.0.1 | POST     "/add_bookmark"
[GIN] 2025/05/21 - 17:50:43 | 200 |    3.039103ms |       127.0.0.1 | GET      "/my_bookmarks"
[GIN] 2025/05/21 - 17:50:47 | 200 |    1.378581ms |       127.0.0.1 | GET      "/snapshot?sid=45f1ff4cae86a7744694c0b953c083bf830475c65e5096da04868cc1ece1bd94&bid=2"
[GIN] 2025/05/21 - 17:50:47 | 200 |     611.499µs |       127.0.0.1 | GET      "/static/data/snapshots/45/45f1ff4cae86a7744694c0b953c083bf830475c65e5096da04868cc1ece1bd94.gz"
[GIN] 2025/05/21 - 17:50:47 | 404 |     700.297µs |       127.0.0.1 | GET      "/static/data/resources/f7/f73533c94a7d6fece2222badb9bd64c25e0d0b1d96edf26cd2985694a3dc854c.svg"
[GIN] 2025/05/21 - 17:50:47 | 404 |    1.199314ms |       127.0.0.1 | GET      "/static/data/resources/37/37502515362b1c080916efd0d3408c105f3ff9b29c17bdd7ea3e3a07b317e308.png"
[GIN] 2025/05/21 - 17:50:47 | 404 |     1.16477ms |       127.0.0.1 | GET      "/static/data/resources/5c/5c59903cb6a4d223eb96dd9942738aa11844e39808dbebf16f2987faf257527b.png"
[GIN] 2025/05/21 - 17:50:47 | 404 |    1.528964ms |       127.0.0.1 | GET      "/static/data/resources/75/75038605ff9e35cc393e0ed8200069601c889100607cde67d2af68b9eb88e5d4.png"
[GIN] 2025/05/21 - 17:50:47 | 404 |    1.206438ms |       127.0.0.1 | GET      "/static/data/resources/f7/f73533c94a7d6fece2222badb9bd64c25e0d0b1d96edf26cd2985694a3dc854c.svg"
[GIN] 2025/05/21 - 17:50:47 | 404 |    1.307648ms |       127.0.0.1 | GET      "/static/data/resources/37/37502515362b1c080916efd0d3408c105f3ff9b29c17bdd7ea3e3a07b317e308.png"
[GIN] 2025/05/21 - 17:50:47 | 404 |    1.034615ms |       127.0.0.1 | GET      "/static/data/resources/37/37502515362b1c080916efd0d3408c105f3ff9b29c17bdd7ea3e3a07b317e308.png"
[GIN] 2025/05/21 - 17:50:47 | 404 |     1.27156ms |       127.0.0.1 | GET      "/static/data/resources/f7/f73533c94a7d6fece2222badb9bd64c25e0d0b1d96edf26cd2985694a3dc854c.svg"
[GIN] 2025/05/21 - 17:50:48 | 404 |     833.717µs |       127.0.0.1 | GET      "/static/data/resources/f7/f73533c94a7d6fece2222badb9bd64c25e0d0b1d96edf26cd2985694a3dc854c.svg"
[GIN] 2025/05/21 - 17:51:01 | 200 |     2.76582ms |       127.0.0.1 | GET      "/my_bookmarks"
```

</p>
</details> 

<details><summary>Check files</summary>
<p>

```shellSession
$ ls static/data/
 snapshots
omnom on  main [?] [ v1.24.3]
$ stat static/data/snapshots/45/45f1ff4cae86a7744694c0b953c083bf830475c65e5096da04868cc1ece1bd94.gz
  File: static/data/snapshots/45/45f1ff4cae86a7744694c0b953c083bf830475c65e5096da04868cc1ece1bd94.gz
  Size: 35699           Blocks: 72         IO Block: 4096   regular file
Device: 0,58    Inode: 67127621    Links: 1
Access: (0600/-rw-------)  Uid: ( 1000/  user)   Gid: (  100/   users)
Access: 2025-05-21 17:49:55.521105139 +0200
Modify: 2025-05-21 17:49:55.521105139 +0200
Change: 2025-05-21 17:49:55.521105139 +0200
 Birth: 2025-05-21 17:49:55.521105139 +0200
```

</p>
</details>
